version: "3.8"

services:
  app:
    build: ./app
    container_name: marx_tec_app
    env_file: .env
    volumes:
      - app-data:/data
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    container_name: marx_tec_nginx
    volumes:
      - ./nginx:/etc/nginx
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
      - "25565:25565"
    depends_on:
      - app
    command: ["/bin/bash", "/etc/nginx/reloader.sh"]

  certbot:
    image: certbot/certbot
    container_name: marx_tec_certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  app-data:
